/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kcc.software;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kcc.software.DatabaseConnection;

/**
 *
 * @author vengatesh
 */
public class mem extends javax.swing.JFrame {

    /**
     * Creates new form mem
     */
    public mem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        memno = new javax.swing.JTextField();
        memname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        village = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paccssbno = new javax.swing.JTextField();
        edccsbno = new javax.swing.JTextField();
        edcckccno = new javax.swing.JTextField();
        aadharno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        phno = new javax.swing.JTextField();
        smartcardno = new javax.swing.JTextField();
        panno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Member No");

        jLabel2.setText("Member Name");

        jLabel3.setText("Father Name");

        jLabel4.setText("Village");

        memno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memnoActionPerformed(evt);
            }
        });

        memname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memnameActionPerformed(evt);
            }
        });

        jLabel5.setText("Paccs SB No");

        jLabel6.setText("EDCC SB No");

        jLabel7.setText("EDCC KCC No");

        jLabel8.setText("Aadhar No");

        jLabel9.setText("Mobile No");

        jLabel10.setText("PAN No");

        jLabel11.setText("Smartcard No");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MODIFY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("MEMBER MASTER");

        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(82, 82, 82)
                .addComponent(jButton3)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(memno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memname)
                            .addComponent(fname)
                            .addComponent(village)
                            .addComponent(phno)
                            .addComponent(smartcardno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paccssbno)
                                    .addComponent(edccsbno, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edcckccno, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(panno)
                                    .addComponent(aadharno))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(memno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(paccssbno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(memname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edccsbno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(edcckccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(village, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(aadharno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(smartcardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      main m=new main();
      m.setVisible(true);
      this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void memnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memnoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jButton1.disable();
       int mno =Integer.parseInt(memno.getText());
       Connection conn;
       DatabaseConnection dbc = new DatabaseConnection();
        conn = dbc.getConnection();
        String qur="SELECT * FROM membermaster where memno="+mno;
        Statement st;
        try {
            st = conn.createStatement();
            ResultSet rs  = st.executeQuery(qur);
            while(rs.next()){
                memno.setText(rs.getString("memno"));
                memname.setText(rs.getString("membername"));
                fname.setText(rs.getString("fathername"));
                village.setText(rs.getString("village"));
                panno.setText(rs.getString("panno"));
                aadharno.setText(rs.getString("aadharno"));
                phno.setText(rs.getString("mobileno"));
                smartcardno.setText(rs.getString("smartcardno"));
                paccssbno.setText(rs.getString("paccssbno"));
                edccsbno.setText(rs.getString("edccsbno"));
                edcckccno.setText(rs.getString("edcckccno"));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(mem.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modify();
        //modiry button
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            int mno =Integer.parseInt(memno.getText());
       Connection conn;
       DatabaseConnection dbc = new DatabaseConnection();
        conn = dbc.getConnection();
        String qur="delete FROM membermaster where memno="+mno;
        Statement st;
        try {
            st = conn.createStatement();
            st.executeQuery(qur);
            JOptionPane.showMessageDialog(this, "Member Deleted : "+mno);
        } catch (SQLException ex) {
            Logger.getLogger(mem.class.getName()).log(Level.SEVERE, null, ex);
        }
        // delete
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mem().setVisible(true);
            }
        });
    }
    public void clearField(){
            memno.setText("");
            memname.setText("");
            fname.setText("");
            village.setText("");
            panno.setText("");
            aadharno.setText("");
            phno.setText("");
            smartcardno.setText("");
            paccssbno.setText("");
            edccsbno.setText("");
            edcckccno.setText("");
    }
    public void update(){
        int mno=Integer.parseInt(memno.getText());
        String mname=memname.getText();
        String faname=fname.getText();
        String v=village.getText();
        String pan=panno.getText();
        String adhar=aadharno.getText();
        int m=Integer.parseInt(phno.getText());
        String rat=smartcardno.getText();
        int pacsb=Integer.parseInt(paccssbno.getText());
        int edccsb=Integer.parseInt(edccsbno.getText());
        int edcckcc=Integer.parseInt(edcckccno.getText());
        
       Connection conn;
       DatabaseConnection dbc = new DatabaseConnection();
        conn = dbc.getConnection();
        String qur = "insert into membermaster(memno,membername,fathername,village,panno,aadharno,mobileno,smartcardno,paccssbno,edccsbno,edcckccno)"
                + "values(?,?,?,?,?,?,?,?,?,?,?);";
        try {
            PreparedStatement ps = conn.prepareStatement(qur);
            ps.setInt(1, mno);
            ps.setString(2, mname);
            ps.setString(3, faname);
            ps.setString(4, v);
            ps.setString(5, pan);
            ps.setBigDecimal(6, new BigDecimal(adhar));
            ps.setInt(7, m);
            ps.setString(8, rat);
            ps.setInt(9, pacsb);
            ps.setInt(10, edccsb);
            ps.setInt(11, edcckcc);
            System.out.println(qur);
           
            ps.execute();
            clearField();
            
            JOptionPane.showMessageDialog(this, "updated");
        } catch (SQLException ex) {
            Logger.getLogger(mem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void modify(){
        int mno=Integer.parseInt(memno.getText());
        String mname=memname.getText();
        String faname=fname.getText();
        String v=village.getText();
        String pan=panno.getText();
        String adhar=aadharno.getText();
        int m=Integer.parseInt(phno.getText());
        String rat=smartcardno.getText();
        int pacsb=Integer.parseInt(paccssbno.getText());
        int edccsb=Integer.parseInt(edccsbno.getText());
        int edcckcc=Integer.parseInt(edcckccno.getText());
        
       Connection conn;
       DatabaseConnection dbc = new DatabaseConnection();
        conn = dbc.getConnection();
        String qur = "update membermaster "
                + "set membername=?,"
                + "fathername=?,"
                + "village=?,"
                + "panno=?,"
                + "aadharno=?,"
                + "mobileno=?,"
                + "smartcardno=?,"
                + "paccssbno=?,"
                + "edccsbno=?,"
                + "edcckccno=?"
                + "where memno="+mno;
        try {
            PreparedStatement ps = conn.prepareStatement(qur);
            
            ps.setString(1, mname);
            ps.setString(2, faname);
            ps.setString(3, v);
            ps.setString(4, pan);
            ps.setBigDecimal(5, new BigDecimal(adhar));
            ps.setInt(6, m);
            ps.setString(7, rat);
            ps.setInt(8, pacsb);
            ps.setInt(9, edccsb);
            ps.setInt(10, edcckcc);
            System.out.println(qur);
            ps.execute();
            clearField();
            
            JOptionPane.showMessageDialog(this, "updated");
        } catch (SQLException ex) {
            Logger.getLogger(mem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadharno;
    private javax.swing.JTextField edcckccno;
    private javax.swing.JTextField edccsbno;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memname;
    private javax.swing.JTextField memno;
    private javax.swing.JTextField paccssbno;
    private javax.swing.JTextField panno;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField smartcardno;
    private javax.swing.JTextField village;
    // End of variables declaration//GEN-END:variables
}
